POST {{baseUrl}}/dev/auction
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title":"some fancy title"
}
###
GET {{baseUrl}}/dev/auctions?status=OsPEN
Authorization: Bearer {{authToken}}
###
GET {{baseUrl}}/dev/auction/48886d7e-57ae-4b43-8849-c670b4e4de30
Authorization: Bearer {{authToken}}

###
PATCH  {{baseUrl}}/dev/auction/1fb7c7c2-7228-41f9-b8c1-d7027d7adf29/bid
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "amount":"41"
}


