POST {{baseUrl}}/dev/auction
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title":"some fancy title"
}
###
GET {{baseUrl}}/dev/auctions?status=OsPEN
Authorization: Bearer {{authToken}}
###
GET {{baseUrl}}/dev/auction/48886d7e-57ae-4b43-8849-c670b4e4de30
Authorization: Bearer {{authToken}}

###
PATCH  {{baseUrl}}/dev/auction/892183fa-9c8b-4ecd-b3aa-8f920ef49edf/bid
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "amount":"41"
}


